### ISSUE TITLE
Refactor properties on the custom element

### ISSUE THREAD

**Issue by drewwills** [cparaiso/form-builder#11]
Currently we have (to the best of my knowledge)...

```
            <form-builder
              fbms-base-url="/fbms/api/v1/forms/"
              fbms-form-name="communication-preferences"
              response-url="/fbms/api/v1/responses/"
              oidc-url="/uPortal/api/v5-1/userinfo">
            </form-builder>
```

Better would be (as far as I can see)...

```
            <form-builder
              fbms-base-url="/fbms"
              fbms-form-fname="communication-preferences"
              oidc-url="/uPortal/api/v5-1/userinfo">
            </form-builder>
```

Differences:
  - `fbms-base-url` does not include the `/api/v1/forms/` path info (which can be hard-coded)
  - `fbms-form-name` has been renamed to `fbms-form-fname`
  - `response-url` is not required (b/c it can be infered from `fbms-base-url` just as easily as the `/forms/` endpoint)

### Also Note

The URI for users' previous responses is `/fbms/api/v1/submissions`, not `/fbms/api/v1/responses`.

**Comment by cparaiso** [comment]
response-url removed and now inferred based on fbms-base-url and fbms-form-fname. updated props/defaults.
