### ISSUE TITLE
Provide a user-friendly message if the /userinfo request fails, and update the README

### ISSUE THREAD

**Issue by drewwills** [cparaiso/form-builder#5]
A lot of people are going to mess up integration with the required REST endpoints the firsts time, which include...

  - The uPortal `/userinfo` endpoint
  - The FBMS `/forms` endpoint
  - The FBMS `/submissions` endpoint

We should...
  - Provide adequate coverage of this step in the README
  - Provide a user-friendly message in the UI if it doesn't work

**Comment by cparaiso** [comment]
Added user friendly message to the UI. on /userinfo and /forms of the fbms.

**Comment by drewwills** [comment]
Awesome @cparaiso -- please don't forget to close the ticket when you've had a chance to touch the other aspects of this ticket.
Also, the bar for coverage in the `README` is not very high.  A few sentences is normally enough.

**Comment by cparaiso** [comment]
integrations for /submissions is inferred by existing properties. error messages for /submissions will be covered in Issue #13
