### ISSUE TITLE
Build form-builder to a single .js file

### ISSUE THREAD

**Issue by drewwills** [cparaiso/form-builder#9]
I just ran the build.  It appears to produce separate .js and .css files.

@cparaiso @ChristianMurphy

**Comment by ChristianMurphy** [comment]
https://www.styled-components.com/ can help

**Comment by cparaiso** [comment]
Thanks @ChristianMurphy! currently the css being built out was, both, the default styling from create-react-app and a couple of modifications i made to make it look good for local dev. All not required in prod build.
